name: Update WordPress.org Assets

on:
  push:
    branches:
      - master
    paths:
      - '.wordpress-org/**'
      - 'readme.txt'
  workflow_dispatch:

jobs:
  asset-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync assets and readme to WordPress.org
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: poll-creator
